Improvements to app documentation
Esri/nearby-javascript pull request #31
Opened 2020-07-31 21:34 UTC by mikewilburn

This PR:
- renames `docs/index.md` to `docs/README.md`
- adds table of contents to (2) README files. The TOC was generated using MDTOC.
- links to `docs/README.md` from the root README.md
- makes small formatting corrections to root README.md
- increments app version to the applicable patch number
- describes patch changes in RELEASE.md

2020-08-05 16:41 UTC, esreli requested changes
Just a few changes :)

2020-08-05 16:41 UTC, esreli commented on RELEASE.md
> +# Release 1.0.2
We may not have these headers consistent from one OSA repo to another but I do think they should remain consistent within each project.
```suggestion
## 1.0.2
```

2020-08-05 16:41 UTC, esreli commented on docs/README.md
> +# Nearby Places JavaScript
The convention has been to name this header 'Contents'. Should we keep doing so?
```suggestion
# Contents
```

2020-08-05 16:41 UTC, esreli commented on RELEASE.md
> +- Comprehensive [app documentation](/documentation/index.md) from the ArcGIS for Developers site.
```suggestion
- Comprehensive [app documentation](/docs/README.md) from the ArcGIS for Developers site.
```

2020-08-06 16:50 UTC, mikewilburn commented on RELEASE.md
> +# Release 1.0.2
Very good catch!

2020-08-06 16:53 UTC, mikewilburn commented on docs/README.md
> +# Nearby Places JavaScript
I don't think we have a single convention. I've been placing a "Contents" header or emboldening one above the TOC when the document has an introductory paragraph and it feels the TOC is better placed after that. In cases such as those, I think a TOC title helps, but when it's immediately at the top of the document, I think the document header naming the app is fine. I'd like to leave this as it is.

2020-08-06 16:56 UTC, mikewilburn commented
@esreli good eyes on the RELEASE doc. I just pushed up fixes to correct those two things. Let me know what you think about my reply to the TOC header discussion.

2020-08-06 16:58 UTC, esreli requested changes
One more docs link fix and I think we're good to go.

2020-08-06 16:58 UTC, esreli commented on RELEASE.md
> +- Comprehensive [app documentation](/documentation/README.md) from the ArcGIS for Developers site.
```suggestion
- Comprehensive [app documentation](/docs/README.md) from the ArcGIS for Developers site.
```

2020-08-06 16:58 UTC, esreli commented on docs/README.md
> +# Nearby Places JavaScript
Sure 👍

2020-08-06 17:56 UTC, mikewilburn commented on RELEASE.md
> +- Comprehensive [app documentation](/documentation/README.md) from the ArcGIS for Developers site.
Oof, don't know how I missed that. Thanks, just corrected.

2020-08-06 17:59 UTC, esreli approved these changes

2020-08-06 18:02 UTC, mikewilburn commented
@odoe do you have any comments on this PR? In particular, can you confirm for me that ea39852 caught the one place in which to update the app version?

2020-08-11 16:57 UTC, odoe approved these changes

2020-08-11 17:00 UTC, merged